import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import { SmoothScrolling } from "@/components/smooth-scrolling";

const mainFont = localFont({
  src: [
    {
      path: "./../../public/fonts/Gilroy-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./../../public/fonts/Gilroy-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../../public/fonts/Gilroy-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./../../public/fonts/Gilroy-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./../../public/fonts/Gilroy-Heavy.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-main",
});

export const metadata: Metadata = {
  title: "Dr. Online",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${mainFont.variable} antialiased`}>
        <Header />
        <SmoothScrolling>
          <main className="bg-brand-dark-green">{children}</main>
        </SmoothScrolling>
        <Footer />
      </body>
    </html>
  );
}
